- hosts: localhost
  connection: local
  become: yes
  tasks:


#  - name: Print all available facts
#    ansible.builtin.debug:
#      var: ansible_facts


  - name: "Add git's PPA (for installing latest git versions"
    ansible.builtin.apt_repository:
      repo: 'ppa:git-core/ppa'
      filename: 'git'

  - name: "Install basic packages"
    apt:
      pkg:
      - apt-transport-https
      - bash-completion
      - ca-certificates
      - curl
      - gettext           # For .po -> .mo language/translation file conversion
      - git
      - gnupg
      - htop
      - iotop
      - lsb-release
      - lynx
      - mc
      - python3-pymysql   # For Ansible's MySQL management module
      - rsyslog           # `apt autoremove` removed this one for some reason
      - nano
      - tig

  - name: "Remove unnecessary packages"
    apt:
      pkg:
      - cowsay   # This one makes ansible output be full of cows, literally.
      state: absent
