- hosts: localhost
  connection: local
  become: yes
  tasks:


  - name: "Install LXC"
    apt:
      pkg:
      - lxc


  - name: "Install the custom port forwarding script"
    copy:
      src: files/custom-port-forwarding.sh
      dest: /root/custom-port-forwarding.sh
      mode: 0755
    register: custom_port_forwarding_script


  - name: "Install the custom port forwarding SystemD unit file"
    copy:
      src: files/custom-port-forwarding.service
      dest: /etc/systemd/system/custom-port-forwarding.service
    register: custom_port_forwarding_service


  - name: "Reload systemd"
    command: "systemctl daemon-reload"
    when: custom_port_forwarding_script.changed or custom_port_forwarding_service.changed
    register: systemd_daemon_reload

  - name: "(Re)Start custom-port-forwarding.service"
    command: "systemctl restart custom-port-forwarding.service"
    when: systemd_daemon_reload.changed
