-   hosts: localhost
    connection: local
    become: yes
    gather_facts: no
    tasks:


    -   name: "SSH: Disable password-based authentication"
        ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^PasswordAuthentication"
            line: "PasswordAuthentication no"
        register: sshd_config_passwordauthentication


    -   name: "SSH: Restart service"
        command: "systemctl restart ssh.service"
        when: sshd_config_passwordauthentication.changed
