-   hosts: localhost
    connection: local
    become: no
    gather_facts: no



    vars_files:
        -   secrets.yml



    module_defaults:
        community.mysql.mysql_user:
            login_host: "mariadb-svc"



    tasks:
    -   name: "sys-user : status-logger : user"
        community.mysql.mysql_user:
            state: present
            name: "status-logger"
            host: '%'
            encrypted: yes
            password: "{{password_hash.mysql.sys.status_logger}}"
            priv: "*.*:PROCESS"
