apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-ao-prod-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  hostPath:
    path: "/data/ao-prod"
  storageClassName: storage-ao-prod-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-ao-prod-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: storage-ao-prod-pv
