-   hosts: localhost
    connection: local
    become: no
    gather_facts: no



    vars_files:
        -   secrets.yml



    module_defaults:
        community.mysql.mysql_user:
            login_host: "mariadb-svc"



    roles:

    -   role: admin_user
        username: "bojan"
        password: "{{password_hash.mysql.admin.bojan}}"

    -   role: admin_user
        username: "bostjan-admin"
        password: "{{password_hash.mysql.admin.bostjan}}"
