-   hosts: localhost
    connection: local
    become: no
    gather_facts: no



    vars_files:
        -   secrets.yml



    module_defaults:
        community.mysql.mysql_user:
            login_host: "mariadb-svc"



    roles:
    # Andraz Jelenc
    -   role: dev_user
        username: "ajelenc"
        password: "{{password_hash.mysql.dev.ajelenc}}"
        privileges:
            '%\_dev\_%.*': 'ALL'
            '%\_stg.*': 'ALL'
            '%\_stg\_%.*': 'ALL'
            '%\_old.*': 'ALL'
            '%\_old\_%.*': 'ALL'

    # Bostjan Skufca Jese
    -   role: dev_user
        username: "bostjan"
        password: "{{password_hash.mysql.admin.bostjan}}"
        privileges:
            '%\_dev\_%.*': 'ALL'
            '%\_stg.*': 'ALL'
            '%\_stg\_%.*': 'ALL'
            '%\_old.*': 'ALL'
            '%\_old\_%.*': 'ALL'
    -   role: dev_user
        username: "bostjan-prod"
        password: "{{password_hash.mysql.admin.bostjan}}"
        privileges:
            '%\_prod.*': 'ALL'
            '%\_prod\_%.*': 'ALL'

    # Jernej Marcun
    -   role: dev_user
        username: "jmarcun"
        password: "{{password_hash.mysql.dev.jmarcun}}"
        privileges:
            '%\_dev\_%.*': 'ALL'
            '%\_stg.*': 'ALL'
            '%\_stg\_%.*': 'ALL'
            '%\_old.*': 'ALL'
            '%\_old\_%.*': 'ALL'

    # Jernej Stern
    -   role: dev_user
        username: "jstern"
        password: "{{password_hash.mysql.dev.jstern}}"
        privileges:
            '%\_dev\_%.*': 'ALL'
            '%\_stg.*': 'ALL'
            '%\_stg\_%.*': 'ALL'
            '%\_old.*': 'ALL'
            '%\_old\_%.*': 'ALL'

    # Gregor Kokalj (Zahodna liga)
    -   role: dev_user
        username: "gregork"
        password: "{{password_hash.mysql.dev.gregork}}"
        privileges:
            'zl\_%.*': 'ALL'
        state: absent   # Confirmed via email he doesn't need this user

    # Ruben Lasan (GRS)
    -   role: dev_user
        username: "roobn0"
        password: "{{password_hash.mysql.dev.roobn0}}"
        privileges:
            'grs\_%.*': 'ALL'
