-   hosts: localhost
    connection: local
    become: yes
    gather_facts: no



    vars_files:
        -   secrets.yml



    vars:
        # Common definition. Can be overridden for each individual admin below.
        additional_groups:
            - "backup"   # To enable access to backups
            - "ao-dev"
            - "ao-stg"
            - "ao-prod"
            - "pd-stg"
            - "pd-prod"



    roles:
    -   role: admin_user
        username: "bostjan"
        password: "{{password_hash.sys.bostjan}}"
        fullname: "Bostjan Skufca Jese"
        additional_groups:
            - "backup"
            - "ao-dev"
            - "ao-stg"
            - "ao-prod"
            - "pd-stg"
            - "pd-prod"
            - "zl-stg"
            - "zl-prod"

    -   role: admin_user
        username: "jnastran"
        password: "{{password_hash.sys.jnastran}}"
        fullname: "Janez Nastran"

    -   role: admin_user
        username: "bojan"
        password: "{{password_hash.sys.bojan}}"
        fullname: "Bojan Hribernik"
