-   hosts: localhost
    connection: local
    become: yes
    gather_facts: no



    roles:
    -   role: admin_user
        username: "bostjan"
        password: "$6$x1PnIFC35H/YmESz$18UTz2tl9VnGtiMU8tyVw8.Ew8E0EfdLcS8iJiS.onV1BkuiOF9fq/k0OgQKCyCfoAKlLnafrQ0Y2b7h1.2uw/"
        fullname: "Bostjan Skufca Jese"

    -   role: admin_user
        username: "jnastran"
        password: "$6$a7U9lJgrsh79C19X$/69wUif9hgOSBVxGEB5otJmWIhus32z7KTJ.ButOBrLETIpY3Yx4BGHSE0dHHkc.rHSV8JsobiNjN4WVkq5Wg."
        fullname: "Janez Nastran"
