-   hosts: localhost
    connection: local
    become: yes
    gather_facts: no



    roles:



    ### AO
    #
    -   role: app_user
        username: "ao-dev"
        datadir_mode: "0775"   # Skip the directory setgid bit, these are per-user contents

    -   role: app_user
        username: "ao-stg"

    -   role: app_user
        username: "ao-prod"



    ### GRS
    #
    -   role: app_user
        username: "grs-stg"

    -   role: app_user
        username: "grs-prod"



    ### PD
    #
    -   role: app_user
        username: "pd-dev"
        datadir_mode: "0775"   # Skip the directory setgid bit, these are per-user contents

    -   role: app_user
        username: "pd-stg"

    -   role: app_user
        username: "pd-prod"



    ### ZL
    #
    -   role: app_user
        username: "zl-stg"

    -   role: app_user
        username: "zl-prod"
