-   hosts: localhost
    connection: local
    become: yes
    gather_facts: no



    roles:



    ### AO
    #
#    -   role: app_user
#        username: "ao-dev"

#    -   role: app_user
#        username: "ao-stg"

#    -   role: app_user
#        username: "ao-prod"



    ### PD
    #
    -   role: app_user
        username: "pd-dev"

    -   role: app_user
        username: "pd-stg"

#    -   role: app_user
#        username: "pd-prod"
