-   hosts: localhost
    connection: local
    become: yes
    gather_facts: no



    vars:
        # Common definition. Can be overridden for each individual admin below.
#        additional_groups:
#            - "ao-stg"
#            - "ao-prod"
#            - "pd-stg"
#            - "pd-prod"



    roles:
    -   role: dev_user
        username: "gregork"
        password: "*"
        fullname: "Gregor Kokalj"
        additional_groups:
            - "zl-stg"
            - "zl-prod"
