-   hosts: localhost
    connection: local
    become: yes
    gather_facts: no



    vars:
        # Common definition. Can be overridden for each individual developer below.
        additional_groups:
            - "backup"
            - "ao-dev"
            - "ao-stg"
            - "pd-dev"
            - "pd-stg"



    roles:



    ### AO/PD
    #
    -   role: dev_user
        username: "ajelenc"
        password: "*"
        fullname: "Andraz Jelenc"

    -   role: dev_user
        username: "jmarcun"
        password: "*"
        fullname: "Jernej Marcun"

    -   role: dev_user
        username: "jstern"
        password: "*"
        fullname: "Jernej Stern"



    ### GRS
    #
    -   role: dev_user
        username: "roobn0"
        password: "*"
        fullname: "Ruben Lasan"
        additional_groups:
            - "backup"
            - "ao-stg"
            - "grs-stg"
            - "grs-prod"
            - "pd-stg"



    ### Zahodna Liga
    #
    -   role: dev_user
        username: "gregork"
        password: "*"
        fullname: "Gregor Kokalj"
        additional_groups:
            - "backup"
            - "zl-stg"
            - "zl-prod"
