-   hosts: localhost
    connection: local
    become: yes
    gather_facts: no



    vars:
        # Common definition. Can be overridden for each individual developer below.
        additional_groups:
            - "backup"
            - "ao-dev"
            - "ao-stg"
            - "pd-dev"
            - "pd-stg"



    roles:



    ### AO/PD
    #
    -   role: dev_user
        username: "jmarcun"
        password: "*"
        fullname: "Jernej Marcun"



    ### Zahodna Liga
    #
    -   role: dev_user
        username: "gregork"
        password: "*"
        fullname: "Gregor Kokalj"
        additional_groups:
            - "backup"
            - "zl-stg"
            - "zl-prod"
