-   hosts: localhost
    connection: local
    become: yes
    gather_facts: no



    vars:
        additional_groups: ""


    roles:
    -   role: sys_user
        username: "backup"
        password: "*"
        fullname: "Original homedir on Ubuntu was /var/backups"
