apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pd-stg-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: "/data/pd-stg"
  storageClassName: storage-pd-stg-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pd-stg-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-pd-stg-pv
