apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-ao-dev-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: "/data/ao-dev"
  storageClassName: storage-ao-dev-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-ao-dev-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-ao-dev-pv
